config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  devise_for :users

  resources :flags, only: [:create, :destroy]

  resources :flags do
    collection do
      post 'multi_create', to: 'flags#multi_create'
    end
  end

  resources :users, only: [:create, :new, :show, :update] do
    resources :review, only: [:new, :create]

    member do
      get :shelf
      get :friends
      post :friend_request
    end

  end

  resources :products, only: [:index, :show] do

    collection do
      get :scan
      get :compare
    end

    member do
      post "like", to: 'products#like'
      post "unlike", to: 'products#unlike'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_friendship
  acts_as_taggable_on :tags
  acts_as_voter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
  has_many :flags
  has_many :reviews, dependent: :destroy
  has_many :ingredients, through: :flags
  validates :first_name, presence: true
  validates :second_name, presence: true
  validates :email, presence: true

  TAG_OPTIONS = ["sensitive skin", "oily skin", "dry skin", "allergens/irritants", "reproductive toxicity", "environmental concerns", "preservatives", "parabens", "fragrance"]

  def full_name
    "#{first_name} #{second_name}"
  end

  def photo_path
    if self.photo.attached?
      @path = self.photo.key
    else
      @path = 'profile_whubsg'
    end
    @path
  end

  def shelf_hash
    @shelf_products = self.find_up_voted_items.group_by { |item| item.category }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @flag_ings = []
    @good_tag_ings = []
    @bad_tag_ings = []
    @normal_ings =[]
    @skintypeicon = ""
    @path = ""
    authorize current_user
  end

  def shelf
    @user = User.find(params[:id])
    @path = ""
    @path_pro = ""
    authorize @user
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :show
    end
    authorize current_user
  end

  def friends
    @user = User.find(params[:id])
    @path = ""
    @path_pro = ""
    authorize @user
  end

  private

  def user_params
    params.require(:user).permit(tag_list: [])
  end
end

app/views/users/friends.html.erb
<%= render 'shared/search' %>

<div class="user-banner">
  <% if @user == current_user %>
    <h2> My Friends</h2>
  <% else %>
    <% if @user.first_name[-1].include?('s') %>
      <h2><%= @user.first_name+"'"+" "+'Friends' %></h2>
    <% else %>
      <h2><%= @user.first_name+'\'s'+ ' '+'Friends' %></h2>
    <% end %>
  <% end %>
  <div class="user-info">
    <%= cl_image_tag @user.photo_path, alt: "user", class: "avatar-large"  %>
  </div>
</div>

<div class="container">

  <div class="friends">

  <% current_user.friends.each do |friend| %>
    <div class="friend card-white d-flex align-items-center">
      <%= cl_image_tag friend.photo_path , alt: "alttext", class: "avatar-large" %>
      <%= link_to shelf_user_path(friend) do %>
        <p class="mx-3 my-0"><%= friend.full_name %></p>
      <% end %>
    </div>
  <% end %>

  </div>
</div>

app/views/users/shelf.html.erb
<%= render 'shared/search' %>
<div class="user-banner">
  <% if @user == current_user %>
    <h2> My Shelf</h2>
  <% else %>
    <% if @user.first_name[-1].include?('s') %>
      <h2><%= @user.first_name+"'"+" "+'Shelf' %></h2>
    <% else %>
      <h2><%= @user.first_name+'\'s'+ ' '+'Shelf' %></h2>
    <% end %>
  <% end %>
  <div class="user-info">
    <%= cl_image_tag @user.photo_path, alt: "user", class: "avatar-large"  %>
  </div>
</div>

<div class="container">


  <div class="my-shelf">
    <div class="product-cards">
      <% @user.shelf_hash.each do |category, products|  %>

        <div class="row">
          <div class="col-12">
            <h2><%= category %></h2>
          </div>
        </div>


        <div class="row">
        <% products.each do |product| %>
          <div class="col-6">
            <%= link_to product_path(product) do %>
               <div class="card-product">
                <%= cl_image_tag product.photo_path, alt: "product" %>
                <strong><p class="mt-2"><%= product.brand %></p></strong>
                <p><%= product.name.truncate(16) %></p>
                <!-- <p><%= product.category.truncate(16) %></p> -->
              </div>
            <% end %>
          </div>
        <% end %>
        </div>

      <% end %>
    </div>


  </div>


</div>

app/views/users/show.html.erb
<div class="user-banner">
  <h2>My Profile</h2>
  <div class="user-info">
    <%= cl_image_tag current_user.photo_path, alt: "user", class: "avatar-large" %>
  </div>

</div>
    <!-- <p style="text-align:center;"><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "text-center" %></p> -->

<div class="container">
  <div class="skin-type card-white">

    <p class="my-skin-type">Skin concerns</p>
    <i class="fas fa-edit btn" data-toggle="modal" data-target="#tagsModal"></i>
    <%= render 'tags/modal' %>

    <div class="skin-types">
      <% current_user.tag_list.each do |tag| %>

        <% if tag == "dry skin" %>
          <% @skintypecolor = "#e0ae8d" %>
          <% @skintypeicon = "fas fa-fire-alt" %>
        <% elsif tag == "oily skin" %>
          <% @skintypecolor = "#ece030" %>
          <% @skintypeicon = "fas fa-tint" %>
        <% elsif tag == "sensitive skin" %>
          <% @skintypecolor = "#a8e28e" %>
          <% @skintypeicon = "fas fa-feather" %>
        <% elsif tag == "fragrance" %>
          <% @skintypecolor = "#ddbff2" %>
          <% @skintypeicon = "fas fa-apple-alt" %>
        <% else %>
          <% @skintypecolor = "#a6caed" %>
          <% @skintypeicon = "fas fa-surprise" %>
        <% end %>

        <div class="card-skin-type">
          <div class="icon" style="border: 3px solid <%= @skintypecolor %>">
            <i class="<%= @skintypeicon %>" style="color: <%= @skintypecolor %>"></i>
          </div>
          <p class="text-center"><%= tag %></p>
        </div>

      <% end %>
    </div>
  </div>

  <div class="my-flag card-white">

    <p class="text-center my-skin-type">Flagged ingredients</p>
    <i class="fas fa-plus btn" data-toggle="modal" data-target="#flagsModal"></i>
    <%= render 'flags/modal', ingredients: Ingredient.all  %>

    <ul class="list-group list-group-flush">
      <% current_user.flags.each do |flag| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="flex align-items-center flag-item">
            <i class="fab fa-font-awesome-flag mr-2"></i>
            <p><%= flag.ingredient.name %></p>
          </div>
          <%= link_to flag_path(flag), method: :delete, data: { confirm: "Are you sure?"} do %>
            <i class="fas fa-times" style="color: lightgray"></i>
          <% end %>
        </li>
      <% end %>

    </ul>

   </div>

</div>