config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  devise_for :users

  resources :flags, only: [:create, :destroy]

  resources :flags do
    collection do
      post 'multi_create', to: 'flags#multi_create'
    end
  end

  resources :users, only: [:create, :new, :show, :update] do
    resources :review, only: [:new, :create]

    member do
      get :shelf
      get :friends
      post :friend_request
    end

  end

  resources :products, only: [:index, :show] do

    collection do
      get :scan
      get :compare
    end

    member do
      post "like", to: 'products#like'
      post "unlike", to: 'products#unlike'
    end
  end

end

app/views/shared/_card-productinfo.html.erb
<div class="card-white">
  <div class="card-white-up flex">

    <div class="product-img">
      <%= cl_image_tag @product.photo_path, alt: "product" %>
    </div>


    <div class="favorite">
      <% if current_user.liked?(@product) %>
        <%= link_to unlike_product_path(@product), method: :post do %>
          <i class="fas fa-heart like"></i>
        <% end %>
      <% else %>
        <%= link_to like_product_path(@product), method: :post do %>
          <i class="far fa-heart unlike"></i>
        <% end %>
      <% end %>
    </div>


    <div class="product-info">
      <div class="product-rating">

        <% if product.reviews.empty? %>

          <p style="font-size: 16px;"><strong>No Ratings yet</strong></p>

        <% else %>

          <div class="score-rating">
              <p id="rate"><%= product.reviews.pluck(:rating).sum / product.reviews.pluck(:rating).length %>.0</p>
              <p id="rating"><%= product.reviews.size %><br>ratings</p>
          </div>

          <div class="stars">
            <% (product.reviews.pluck(:rating).sum / product.reviews.pluck(:rating).length).times do %>
              <i class="fas fa-star" id="star-pink"></i>
            <% end %>

            <% (5 - product.reviews.pluck(:rating).sum / product.reviews.pluck(:rating).length).times do %>
              <i class="fas fa-star" id="star-gray"></i>
            <% end %>
          </div>
        <% end %>
      </div>

      <button class="btn btn-flat mt-3" data-toggle="modal" data-target="#compareModal">Compare</button>
      <%= render 'comparemodal', first_product: @product, products: Product.all, path: @path %>

    </div>

  </div>
  <div class="card-white-bottom">
    <h5><%= product.name %></h5>
    <p><%= product.brand %></p>
    <p><%= product.category %></p>
    <hr>
    <p><%= product.description %></p>
  </div>
</div>

app/views/shared/_card-review.html.erb
<div class="card-white flex">

  <div class="review-user">
    <%= link_to shelf_user_path(review.user)  do %>
    <%= cl_image_tag review.user.photo_path, alt: "user", class: "avatar"  %>
    <p><%= review.user.first_name %></p>
    <% end %>
  </div>

  <div class="review">

    <div class="title-and-star">
      <div class="stars">
        <% (review.rating).times do %>
          <i class="fas fa-star" id="star-pink"></i>
        <% end %>
        <% (5 - review.rating).times do %>
          <i class="fas fa-star" id="star-gray"></i>
        <% end %>
      </div>
      <div class="review-title">
        <p><%= review.title %></p>
      </div>
    </div>

    <div class="review-content">
      <p><%= review.content %></p>
    </div>

  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_friend-review.html.erb
<div class="card-border flex">

  <% if review.user.photo.attached? %>
    <% @path = review.user.photo.key %>
  <% else %>
    <% @path = 'profile_whubsg' %>
  <% end %>




  <div class="review-user">
    <%= link_to shelf_user_path(review.user)  do %>
    <%= cl_image_tag @path, alt: "user", class: "avatar"  %>
    <p><%= review.user.first_name %></p>
    <% end %>
  </div>

  <div class="review">

    <div class="title-and-star">
      <div class="stars">
        <% (review.rating).times do %>
          <i class="fas fa-star" id="star-pink"></i>
        <% end %>
        <% (5 - review.rating).times do %>
          <i class="fas fa-star" id="star-gray"></i>
        <% end %>
      </div>
      <div class="review-title">
        <p><%= review.title %></p>
      </div>
    </div>

    <div class="review-content">
      <p><%= review.content %></p>
    </div>

  </div>

</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar-mobile">

    <%= link_to root_path do %>
      <%= image_tag "home.png", alt: "home", class: "navbar-img" %>
    <% end %>

    <%= link_to friends_user_path(current_user) do %>
      <i class="fas fa-user-friends navbar-img"></i>
    <% end %>


    <%= link_to scan_products_path do %>
      <%= image_tag "scan.png", alt: "scan", class: "navbar-img" %>
    <% end %>

    <% if user_signed_in? %>

      <%= link_to shelf_user_path(current_user) do %>
        <%= image_tag "cosmetics.png", alt: "user", class: "navbar-img" %>
      <% end %>

      <%= link_to user_path(current_user) do %>
        <%= image_tag "user.png", alt: "user", class: "navbar-img" %>
      <% end %>

    <% else %>

      <%= link_to new_user_session_path do %>
        <%= image_tag "cosmetics.png", alt: "user", class: "navbar-img" %>
      <% end %>

      <%= link_to new_user_session_path do %>
        <%= image_tag "user.png", alt: "user", class: "navbar-img" %>
      <% end %>
    <% end %>


</div>

app/views/shared/_search.html.erb
<%= form_tag products_path, method: :get, class: "search-form" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control search-form-control rounded-0",
    placeholder: "Search"
  %>
  <%= button_tag type: 'submit', class: 'rounded-0 btn btn-flat' do %>
    <i class="fas fa-search" style="color: white;"></i>
  <% end %>
<% end %>