config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  devise_for :users

  resources :flags, only: [:create, :destroy]

  resources :flags do
    collection do
      post 'multi_create', to: 'flags#multi_create'
    end
  end

  resources :users, only: [:create, :new, :show, :update] do
    resources :review, only: [:new, :create]

    member do
      get :shelf
      get :friends
      post :friend_request
    end

  end

  resources :products, only: [:index, :show] do

    collection do
      get :scan
      get :compare
    end

    member do
      post "like", to: 'products#like'
      post "unlike", to: 'products#unlike'
    end
  end

end

app/models/flag.rb
class Flag < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

app/controllers/flags_controller.rb
class FlagsController < ApplicationController
  def create
    @flag = Flag.new(flag_params)
    @flag.user = current_user
    @flag.save
    authorize @flag
    if params[:flag][:product_id]
      redirect_to product_path(params[:flag][:product_id].to_i)
    else
      redirect_to user_path(current_user)
    end
  end

  def multi_create
    params[:flags][:id].each do |ingredient_id|
      flag = Flag.new(ingredient: Ingredient.find(ingredient_id), user: current_user)
        authorize flag
      unless flag.save
        render 'users/show'
      end
    end
    redirect_to user_path(current_user)
  end

  def destroy
    @flag = Flag.find(params[:id])
      authorize @flag
    @flag.destroy
    redirect_to user_path(current_user)
  end

  private

  def flag_params
    params.require(:flag).permit(:ingredient_id)
  end
end

app/views/flags/_modal.html.erb
<div class="modal fade" id="flagsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body form-tag">
        <p>Add flags</p>
        <%= simple_form_for :flags, url: multi_create_flags_path, method: :post do |f| %>
          <%= f.input :id, placeholder: 'Add flags', label: false, as: :select, input_html: {class:'select2', multiple:'multiple'}, collection:
                ingredients
                .sort_by { |ingredient| ingredient.name }, include_hidden: false %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-light-gray" data-dismiss="modal">Close</button>
          <%= f.submit class: "btn btn-sky"%>
        <% end %>
      </div>
    </div>
  </div>
</div>