config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  devise_for :users

  resources :flags, only: [:create, :destroy]

  resources :flags do
    collection do
      post 'multi_create', to: 'flags#multi_create'
    end
  end

  resources :users, only: [:create, :new, :show, :update] do
    resources :review, only: [:new, :create]

    member do
      get :shelf
      get :friends
      post :friend_request
    end

  end

  resources :products, only: [:index, :show] do

    collection do
      get :scan
      get :compare
    end

    member do
      post "like", to: 'products#like'
      post "unlike", to: 'products#unlike'
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_votable
  has_many :products_ingredients
  has_many :reviews
  has_many :ingredients, through: :products_ingredients

  has_one_attached :photo
  validates :name, presence: true
  validates :category, presence: true
  validates :brand, presence: true

  include PgSearch::Model
    pg_search_scope :global_search,
    against: [ :name, :brand, :category ],
    associated_against: {
      ingredients: [ :name ]
    },
    using: {
      tsearch: { prefix: true }
    }

  def ingredients_tag_list_good
    ingredients.map(&:tag_list).flatten.uniq.delete_if {|ingredient| ingredient.start_with?("bad")}
  end

  def related_products
    # Ingredient.tagged_with(ingredients_tag_list_good, any: true).map(&:products).flatten.uniq.select { |product| product.category == category}.first(5)
    Ingredient.tagged_with(ingredients_tag_list_good, any: true).map(&:products).flatten.uniq.select { |product| product.category == category}.sort_by(&:created_at).first(5)
  end


  def photo_path
    if self.photo.attached?
      @path = self.photo.key
    else
      @path = 'no_image'
    end
    @path
  end

  def count_bad(user)
    @count = 0
    self.ingredients.each do |ingredient|
      if user.tag_list.map {|tag| "bad for #{tag}" }.include?(ingredient.tag_list.first)
        @count += 1
      elsif user.ingredients.include?(ingredient)
        @count += 1
      end
    end
    @count
  end

  def count_good(user)
    @count = 0
    self.ingredients.each do |ingredient|
      @count += 1 if user.tag_list.map {|tag| "good for #{tag}" }.include?(ingredient.tag_list.first)
    end
    @count
  end


  def flag_ings(user)
    @flag_ings = []

    self.ingredients.each do |ingredient|
      @flag_ings << ingredient if user.ingredients.include?(ingredient)
    end

    @flag_ings
  end

  def badtag_ings(user)
    @badtag_ings = []

    self.ingredients.each do |ingredient|
      @badtag_ings << ingredient if user.tag_list.map {|tag| "bad for #{tag}" }.include?(ingredient.tag_list.first)
    end
    @badtag_ings
  end

  def goodtag_ings(user)
    @goodtag_ings = []

    self.ingredients.each do |ingredient|
      @goodtag_ings << ingredient if user.tag_list.map {|tag| "good for #{tag}" }.include?(ingredient.tag_list.first)
    end
    @goodtag_ings
  end

  def normal_ings(user)
    @normal_ings = []

    self.ingredients.each do |ingredient|
      unless user.ingredients.include?(ingredient) || user.tag_list.map {|tag| "good for #{tag}" }.include?(ingredient.tag_list.first) || user.tag_list.map {|tag| "bad for #{tag}" }.include?(ingredient.tag_list.first)
        @normal_ings << ingredient
      end
    end
    @normal_ings
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    if params[:query].present?
      @products = policy_scope(Product).global_search(params[:query])
    else
      @products = policy_scope(Product)
    end
  end

  def like
    product = Product.find(params[:id])
    authorize product
    current_user.likes(product)
    redirect_to product_path(product)
  end

  def unlike
    product = Product.find(params[:id])
    authorize product
    current_user.unlike(product)
    redirect_to product_path(product)
  end

  def show
    @path = ""
    @count = 0
    @product =
      if params[:barcode].blank?
        Product.find(params[:id])
      else
        Product.find_by_barcode(params[:barcode])
      end
    authorize @product
  end

  def scan
    authorize Product
  end


  def compare
    @count = 0
    @first_product = Product.find(params["products"]["first_product"].to_i)
    @second_product = Product.find(params["products"]["id"].first)

    @common_ings = @first_product.ingredients & @second_product.ingredients
    @only_first_ings = @first_product.ingredients - @second_product.ingredients
    @only_second_ings = @second_product.ingredients - @first_product.ingredients

    authorize Product
  end



end

app/views/products/_comparemodal.html.erb
<div class="modal fade" id="compareModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body form-tag">



        <div class="card-product">
          <%= cl_image_tag first_product.photo_path, alt: "product" %>
          <p class="mt-2"><%= first_product.brand %></p>
          <p><%= first_product.name %></p>
          <p><%= first_product.category %></p>
        </div>


        <%= simple_form_for :products, url: compare_products_path, method: :get do |f| %>
          <%= f.input :id, hint: 'Search and Choose a Product to compare with', label: false, as: :select, input_html: {class:'select3'}, collection:
                products.sort_by { |product| product.name }, include_hidden: false %>
          <%= f.input :first_product, as: :hidden, :input_html => { :value => first_product.id } %>

      </div>
      <div class="modal-footer">

        <button type="button" class="btn btn-light-gray" data-dismiss="modal">Close</button>
          <%= f.submit "compare", class: "btn btn-sky"%>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/products/compare.html.erb
<div class="container">

  <div class="white-big-card my-3 p-3">
    <div class="row">
      <div class="col-12">
        <h2 class="my-3">Product overview</h2>
      </div>
    </div>

    <div class="row px-3">
      <div class="col-6">
        <%= link_to product_path(@first_product) do %>
          <%= cl_image_tag @first_product.photo_path, alt: "first_product", class: "img-compare" %>
          <p><%= @first_product.brand %></p>
          <p><%= @first_product.name %></p>
        <% end %>
      </div>
      <div class="col-6">
        <%= link_to product_path(@second_product) do %>
          <%= cl_image_tag @second_product.photo_path, alt: "second_product", class: "img-compare" %>
          <p><%= @second_product.brand %></p>
          <p><%= @second_product.name %></p>
        <% end %>
      </div>
    </div>

    <hr>
    <div class="row">
      <div class="col-12">
        <p>Category</p>
      </div>
    </div>

    <div class="row px-3">
      <div class="col-6">
        <p><%= @first_product.category %></p>
      </div>
      <div class="col-6">
        <p><%= @second_product.category %></p>
      </div>
    </div>

    <hr>
    <div class="row">
      <div class="col-12">
        <p>Reviews</p>
      </div>
    </div>

    <div class="row px-3">
      <div class="col-6">
        <% if @first_product.reviews.empty? %>
          <p>No Ratings yet</p>
        <% else %>
          <div class="score-rating">
            <p id="rate"><%= @first_product.reviews.pluck(:rating).sum / @first_product.reviews.pluck(:rating).length %>.0</p>
            <p id="rating"><%= @first_product.reviews.size %><br>ratings</p>
          </div>
          <div class="stars">
            <% (@first_product.reviews.pluck(:rating).sum / @first_product.reviews.pluck(:rating).length).times do %>
              <i class="fas fa-star" id="star-pink"></i>
            <% end %>
            <% (5 - @first_product.reviews.pluck(:rating).sum / @first_product.reviews.pluck(:rating).length).times do %>
              <i class="fas fa-star" id="star-gray"></i>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="col-6">

        <% if @second_product.reviews.empty? %>
          <p>No Ratings yet</p>
        <% else %>
          <div class="score-rating">
            <p id="rate"><%= @second_product.reviews.pluck(:rating).sum / @second_product.reviews.pluck(:rating).length %>.0</p>
            <p id="rating"><%= @second_product.reviews.size %><br>ratings</p>
          </div>
          <div class="stars">
            <% (@second_product.reviews.pluck(:rating).sum / @second_product.reviews.pluck(:rating).length).times do %>
              <i class="fas fa-star" id="star-pink"></i>
            <% end %>
            <% (5 - @second_product.reviews.pluck(:rating).sum / @second_product.reviews.pluck(:rating).length).times do %>
              <i class="fas fa-star" id="star-gray"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <hr>
    <div class="row">
      <div class="col-12">
        <p>Total number ingredients</p>
      </div>
    </div>

    <div class="row px-3">
      <div class="col-6">
        <p><%= @first_product.ingredients.count %></p>
      </div>
      <div class="col-6">
        <p><%= @second_product.ingredients.count %></p>
      </div>
    </div>



    <hr>

    <div class="row">
      <div class="col-12">
        <p>Good ingredients</p>
      </div>
    </div>

    <div class="row px-3">

      <div class="col-6">
        <% if @first_product.count_good(current_user) == 0 %>
          <i class="fas fa-surprise green"></i>
          <p>0</p>
        <% else %>
          <div class="accordion-wrap">
            <div class="accordion-item" style="margin-top: 0;">
              <i class="far fa-thumbs-up green"></i>
              <p class="accordion-header"><%= @first_product.count_good(current_user) %></p><i class="fa fa-angle-down" aria-hidden="true"></i>
            </div>

            <div class="accordion-text">
              <ul class="list-group list-group-flush">
                <% @first_product.goodtag_ings(current_user).each do |ingredient| %>
                  <li class="list-group-item d-flex justify-content-center align-items-center">
                    <i class="<%= ingredient.icon %> mr-2" style="color: gray"></i>
                    <p style="color: gray"><%= ingredient.name %></p>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>

      <div class="col-6">
        <% if @second_product.count_good(current_user) == 0 %>
          <i class="fas fa-surprise green"></i>
          <p>0</p>
        <% else %>
          <div class="accordion-wrap">
            <div class="accordion-item" style="margin-top: 0;">
              <i class="far fa-thumbs-up green"></i>
              <p class="accordion-header"><%= @second_product.count_good(current_user) %></p><i class="fa fa-angle-down" aria-hidden="true"></i>
            </div>

            <div class="accordion-text">
              <ul class="list-group list-group-flush">
                <% @second_product.goodtag_ings(current_user).each do |ingredient| %>
                  <li class="list-group-item d-flex justify-content-center align-items-center">
                    <i class="<%= ingredient.icon %> mr-2" style="color: gray"></i>
                    <p style="color: gray"><%= ingredient.name %></p>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>



    </div>









    <hr>
    <div class="row">
      <div class="col-12">
        <p>Bad ingredients</p>
      </div>
    </div>

    <div class="row px-3">
      <div class="col-6">
        <% if @first_product.count_bad(current_user) == 0 %>
          <i class="far fa-thumbs-up green"></i>
          <p>0</p>
        <% else %>
          <div class="accordion-wrap">
            <div class="accordion-item" style="margin-top: 0;">
              <i class="fab fa-font-awesome-flag red"></i>
              <p class="accordion-header"><%= @first_product.count_bad(current_user) %></p><i class="fa fa-angle-down" aria-hidden="true"></i>
            </div>

            <div class="accordion-text">
              <ul class="list-group list-group-flush">
                <% @first_product.flag_ings(current_user).each do |ingredient| %>
                  <li class="list-group-item d-flex justify-content-center align-items-center">
                    <p style="color: gray"><%= ingredient.name %></p>
                  </li>
                <% end %>
                <% @first_product.badtag_ings(current_user).each do |ingredient| %>
                  <li class="list-group-item d-flex justify-content-center align-items-center">
                    <i class="<%= ingredient.icon %> mr-2" style="color: gray"></i>
                    <p style="color: gray"><%= ingredient.name %></p>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>



      <div class="col-6">
        <% if @second_product.count_bad(current_user) == 0 %>
          <i class="far fa-thumbs-up green"></i>
          <p>0</p>
        <% else %>
          <div class="accordion-wrap">
            <div class="accordion-item" style="margin-top: 0;">
              <i class="fab fa-font-awesome-flag red"></i>
              <p class="accordion-header"><%= @second_product.count_bad(current_user) %></p><i class="fa fa-angle-down" aria-hidden="true"></i>
            </div>
            <div class="accordion-text">
              <ul class="list-group list-group-flush">
                <% @second_product.flag_ings(current_user).each do |ingredient| %>
                  <li class="list-group-item d-flex justify-content-center align-items-center">
                    <p style="color: gray"><%= ingredient.name %></p>
                  </li>
                <% end %>
                <% @second_product.badtag_ings(current_user).each do |ingredient| %>
                  <li class="list-group-item d-flex justify-content-center align-items-center">
                    <i class="<%= ingredient.icon %> mr-2" style="color: gray"></i>
                    <p style="color: gray"><%= ingredient.name %></p>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="white-big-card my-3 p-3">
    <div class="row">
      <div class="col-12">
        <h2 class="my-3">Ingredient overview</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-12">

        <div class="accordion-wrap">

          <div class="accordion-item">
            <p class="accordion-header">Common ingredients (<%= @common_ings.count %>)</p><i class="fa fa-angle-down" aria-hidden="true"></i>
          </div>

          <div class="accordion-text">
            <% @common_ings.each do |ing| %>
              <p style="color: gray"><%= ing.name %></p>
            <% end %>
          </div>

        </div>
      </div>
    </div>

    <hr>

    <div class="row">
      <div class="col-12">
        <div class="accordion-wrap">
          <div class="accordion-item">
            <p class="accordion-header">only in <%= @first_product.name %> (<%= @only_first_ings.count %>)</p><i class="fa fa-angle-down" aria-hidden="true"></i>
          </div>
          <div class="accordion-text">
            <% @only_first_ings.each do |ing| %>
              <p style="color: gray"><%= ing.name %></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <hr>
     <div class="row">
      <div class="col-12">
        <div class="accordion-wrap">
          <div class="accordion-item">
            <p class="accordion-header">only in <%= @second_product.name %> (<%= @only_second_ings.count %>)</p><i class="fa fa-angle-down" aria-hidden="true"></i>
          </div>
          <div class="accordion-text">
            <% @only_second_ings.each do |ing| %>
              <p style="color: gray"><%= ing.name %></p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <a href="#top" class="btn btn-ghost">Go to top</a>
    </div>
  </div>

</div>

app/views/products/index.html.erb
<%= render 'shared/search' %>
<div class="container">

  <% if @products.count == 1 %>
    <h4>Found <%= @products.count %> result:</h4>
  <% else %>
    <h4>Found <%= @products.count %> results:</h4>
  <% end %>

  <div class="product-cards">

    <% @products.each do |product| %>
      <%= link_to product_path(product) do %>
        <div class="card-product">
          <%= cl_image_tag product.photo_path, alt: "product" %>
          <p class="mt-2"><%= product.brand.truncate(16) %></p>
          <p><%= product.name.truncate(16) %></p>
          <p><%= product.category.truncate(16) %></p>
        </div>
      <% end %>

    <% end %>

  </div>
</div>

app/views/products/scan.html.erb
<!-- <script src="https://cdn.jsdelivr.net/npm/scandit-sdk@4.x"></script> -->
<div id="scandit-barcode-picker"></div>
<%= form_tag 'products/barcode', method: :get, id: 'barcode-form' do %>
  <%= hidden_field_tag :barcode,
    params[:barcode]
  %>
<% end %>
<script src="https://cdn.jsdelivr.net/npm/scandit-sdk@4.x"></script>
<!-- <script src="/node_modules/scandit-sdk/build/browser/index.min.js"></script> -->
<!-- <script type="module" src="/node_modules/scandit-sdk/build/browser/index.esm.min.js"></script> -->
<script>
  function continueScanning() {
    if (picker) {
      // continueButton.disabled = true;
      picker.resumeScanning();
    }
  }
  const licenseKey =
    "AR7OBxXCC+FZEslnBTT41oEcEW1AKpDltX+CVDt4PQx5aHRkP3XgnNl/UavvXJi6EnBolO8VVzMDCbXGD1Eth15vxXpiRX2x9A+luUlViEWBXVVtfiRxI+EsLLfkFKRaTzKPXeQYsXVlP3lwdB5u1cjLo7IL/tv/Rf7lDWcSJtuxMV3DnjGecInoMfQtVjAbGvuB/jkSrKrCm0V0eokSijXXznHP7t1dC1j2x2gWeDDgnmQvgIyV4U3lBYE20hlT9XYjtJfubvSgWGYrDwYp6HzzWS50bbX8VQFFHQyD9peiA7DaL5aaTQbisoUOO9jsXhhXcKHCFHYRNoAQdjloAxi0D0GRbwBIfCp4OmHn32zS0D43h/6LFtu2XjCNsCX0G5+iKDQWCI978Nf8Si07xK6YghEHYAgYuspx+xab2lc4FQInNJXzwZmKGvr0X+27vAJV9cGjIq57pqd8SWflsFFapIESuHjErygX17i/uSI3BaqHdsi05qe9PubQ7klPya4CBFhHU2Qi2DDHX7Yt7zAmJZmKqnLMTjgGI1vrunV9AwChb4lLp3cLn9RW6otZ57c65xCXGSmQtZNsAIMly9M08WrPPHlGNaNbDrr56Q/ivXBj/qTdmzOYX1bdLZBsp/8I8Cah5IbkuX/I9fEdMxx4BTGxl0LtUoe1OZjkl+zyOU73F74e8qVaqOwf1tEl87Q8+96umPT73M63mJpmfel1A5XhWafcbB55dHrlPeTLJ9giLHcRHoVhFcjWZ6tjCSQGaXlVWwBYcciAXZAds/DoU9p8629QKiY0Bmz9v+l6a3rvbaY=";
  const engineLocation =
    "https://cdn.jsdelivr.net/npm/scandit-sdk@4.x/build";
  ScanditSDK.configure(licenseKey, { engineLocation: engineLocation });
  const scannerContainer = document.getElementById(
    "scandit-barcode-picker"
  );
  const resultContainer = document.getElementById("scandit-barcode-result");
  // const continueButton = document.getElementById(
  //   "continue-scanning-button"
  // );
  const barcodeInput = document.getElementById("barcode")
  // continueButton.disabled = true;
  // continueButton.hidden = true;
  let picker;
  ScanditSDK.BarcodePicker.create(scannerContainer, {
    playSoundOnScan: true,
    vibrateOnScan: true
  })
    .then(barcodePicker => {
      picker = barcodePicker;
      const scanSettings = new ScanditSDK.ScanSettings({
        enabledSymbologies: [
          "ean8",
          "ean13",
          "upca",
          "upce",
          "code128",
          "code39",
          "code93",
          "itf"
        ],
        codeDuplicateFilter: 1000
      });
      picker.applyScanSettings(scanSettings);
      picker.on("scan", scanResult => {
        console.log(scanResult.barcodes)
        document.getElementById('barcode').value = scanResult.barcodes[0].data;
        document.getElementById('barcode-form').submit()
        // alert(scanResult.barcodes.reduce(function(string, barcode) {
        //   return string + ScanditSDK.Barcode.Symbology.toHumanizedName(barcode.symbology) + ": " + barcode.data + "\n";
        // }, ""));
      });
      picker.on("scanError", error => {
        console.error(error.message);
      });
      picker.resumeScanning();
    })
    .catch(error => {
      alert(error);
    });
</script>

app/views/products/show.html.erb
<% content_for :meta_title, "#{@product.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @product.description %>
<% content_for :meta_image, cl_image_path(@product.photo) %>

<%= render 'shared/search' %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">

      <div class="product">
        <%= render 'shared/card-productinfo', product: @product, path: @path %>
      </div>

      <div class="card-flag">
        <h5>Relevant for you:</h5>

        <% if @product.count_good(current_user) != 0  %>
          <div class="border-green d-flex">
            <i class="far fa-thumbs-up green"></i>
            <p><%= @product.count_good(current_user) %> good ingredient</p>
          </div>
        <% end %>

        <% if @product.count_bad(current_user) == 0 %>
          <div class="border-green d-flex">
            <i class="far fa-thumbs-up green"></i>
            <p>0 bad ingredient</p>
          </div>
        <% else %>
          <div class="border-red d-flex">
            <i class="fab fa-font-awesome-flag red"></i>
            <p><%= @product.count_bad(current_user) %> bad ingredients</p>
          </div>
        <% end %>

        <div class="border-green d-flex">
          <i class="far fa-smile green"></i>
          <% count = 0 %>
          <% current_user.friends.each do |friend| %>
            <% if friend.voted_up_on? @product %>
              <% count += 1 %>
            <% end %>
          <% end %>
          <% if count == 1 %>
            <p>1 friend is using this product</p>
          <% else %>
            <p style="text-align: left;"><%= count %> friends are using this product</p>
          <% end %>
        </div>
      </div>

    </div>

  </div>



  <div class="text-center">
    <ul class="nav nav-pills justify-content-center my-3" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Ingredients (<%= @product.ingredients.count %>)</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Reviews (<%= @product.reviews.count %>)</a>
      </li>
    </ul>
  </div>

  <div class="tab-content" id="myTabContent">

    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <div class="col-xs-12 col-sm-8 offset-sm-2">
        <div class="ingredients">
          <div class="card-white">
            <ul class="list-group list-group-flush">

            <% @product.goodtag_ings(current_user).each do |ingredient| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <p><%= ingredient.name %></p>
                <div class="flex align-items-center flag-item"><i class="<%= ingredient.icon %> mr-2" style="color: <%= ingredient.color %>"></i><p style="color: #aaa2a2"><%= ingredient.tag_list.first %></p></div>
              </li>
            <% end %>

            <% @product.badtag_ings(current_user).each do |ingredient| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <p><%= ingredient.name %></p>
                <div class="flex align-items-center flag-item"><i class="<%= ingredient.icon %> mr-2" style="color: <%= ingredient.color %>"></i><p style="color: #aaa2a2"><%= ingredient.tag_list.first %></p></div>
              </li>
            <% end %>

            <% @product.flag_ings(current_user).each do |ingredient| %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <p><%= ingredient.name %></p>
                <div class="flex align-items-center flag-item"><i class="fab fa-font-awesome-flag mr-2"></i></div>
              </li>
            <% end %>

            <div class="accordion-wrap">
              <div class="accordion-item">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  <p class="accordion-header">more ingredients (<%= @product.normal_ings(current_user).count %>)</p><i class="fa fa-angle-down" aria-hidden="true"></i>
                </li>
              </div>

              <div class="accordion-text">
                <% @product.normal_ings(current_user).each do |ingredient| %>
                  <li class="list-group-item d-flex justify-content-between align-items-center">
                    <p><%= ingredient.name %></p>
                    <%= simple_form_for(Flag.new) do |f| %>
                      <%= f.association :ingredient, as: :hidden, input_html: {value: ingredient.id} %>
                      <%= f.input :product_id, as: :hidden, input_html: {value: @product.id} %>
                      <%= button_tag class: "border-0" do %>
                        <i class="fas fa-plus"></i>
                      <% end %>
                    <% end %>
                  </li>
                <% end %>

              </div>

            </div>
            </ul>
          </div>
        </div>
      </div>
    </div>


    <% friend_reviews = [] %>
    <% random_reviews = [] %>

    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <div class="reviews">
      <div class="col-xs-12 col-sm-8 offset-sm-2">
        <% @product.reviews.each do |review| %>
          <% if current_user.friends.include?(review.user) %>
            <% friend_reviews << review %>
          <% else %>
            <% random_reviews << review %>
          <% end %>
        <% end %>

        <% if @product.reviews.empty? %>
          <p style="font-size: 16px;"><strong>No Reviews yet</strong></p>
        <% elsif friend_reviews.empty? %>
          <% @product.reviews.each do |review| %>
          <%= render 'shared/card-review', review: review %>
          <% end %>
        <% else %>
          <h5>Reviews from friends</h5>
          <% friend_reviews.each do |review| %>
            <%= render 'shared/friend-review', review: review %>
            <% end %>
          <h5>Other Reviews</h5>
            <% random_reviews.each do |review| %>
            <%= render 'shared/card-review', review: review %>
            <% end %>
          <% end %>
      </div>
    </div>
    </div>

  </div>

  <p class="text-center mt-5">Related products (<%= @product.related_products.size %>)</p>

  <div class="owl-carousel owl-theme">
    <% @product.related_products.each do |product| %>
      <% if product == @product %>
      <% else %>
        <%= link_to product_path(product) do %>
          <div class="card-product">
            <%= cl_image_tag product.photo_path , alt: "product" %>
            <p class="mt-2"><%= product.brand.truncate(16) %></p>
            <p><%= product.name.truncate(16) %></p>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <%= content_for(:after_js) do %>
  <script type="text/javascript">
    $('.owl-carousel').owlCarousel({
      stagePadding: 50,
      loop:true,
      autoplay:true,
      autoplaySpeed:10000,
      margin:10,
      nav:true,
      responsive:{
          0:{
              items:1
          },
          600:{
              items:3
          }
      }
  })
  </script>
  <% end %>

  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-8">
      <div class="d-flex justify-content-center">
        <a href="#top" class="btn btn-ghost">Go to top</a>
      </div>
    </div>
  </div>

</div>